version: "2"
#Version of the docker-compose
services:
#Containers will be run under the same docker network
 mongodb-main:
    image: mongo:latest
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/data:/data/db
      - ./config:/config
#Directories
    ports:
      - 27027:27017
    networks:
      docker_default:
#[Host port]:[container port]
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal","--dbpath","/data/db","--smallfiles","--keyFile","/config/mongodb-keyfile","--auth" ]
#Where the container starts to run
#--Smallfiles : reduce disk usage
#--replSet : Name of replication 
#--journal : A recovery for failure
 mongodb-sub1:
    image: mongo:latest
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb2/data:/data/db
      - ./config:/config
    ports:
      - 27028:27017
    networks:
      docker_default:
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal","--dbpath","/data/db","--smallfiles","--keyFile","/config/mongodb-keyfile" ,"--auth"]

 mongodb-sub2:
    image: mongo:latest
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb3/data:/data/db
      - ./config:/config
    ports:
      - 27029:27017
    networks:
      docker_default:
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal","--dbpath","/data/db","--smallfiles","--keyFile","/config/mongodb-keyfile","--auth"]
networks:
    docker_default:
        driver: bridge